# Generated by Django 4.0.2 on 2022-02-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
